# Generated by Django 4.2.5 on 2023-10-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.AddField(
            model_name="date",
            name="city",
            field=models.CharField(
                default="", max_length=200, verbose_name="Población"
            ),
        ),
        migrations.AddField(
            model_name="date",
            name="phone",
            field=models.CharField(default="", max_length=100, verbose_name="Teléfono"),
        ),
        migrations.AddField(
            model_name="date",
            name="street",
            field=models.CharField(default="", max_length=200, verbose_name="Calle"),
        ),
    ]
