# Generated by Django 4.2.5 on 2023-10-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_delete_address_date_city_date_phone_date_street"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="date",
            name="day",
        ),
        migrations.RemoveField(
            model_name="date",
            name="hour",
        ),
        migrations.AddField(
            model_name="date",
            name="laboral",
            field=models.CharField(
                default="", max_length=100, verbose_name="Horario L-V"
            ),
        ),
        migrations.AddField(
            model_name="date",
            name="saturday",
            field=models.CharField(
                default="", max_length=100, verbose_name="Horario Sábado"
            ),
        ),
        migrations.AddField(
            model_name="date",
            name="sunday",
            field=models.CharField(
                default="", max_length=100, verbose_name="Horario Domingo"
            ),
        ),
    ]
