# Generated by Django 4.2.5 on 2023-09-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Services", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["-created"],
                "verbose_name": "servicio",
                "verbose_name_plural": "servicios",
            },
        ),
        migrations.AlterField(
            model_name="service",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualización"
            ),
        ),
    ]
